import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import ThemeProviderContainer from '@/components/themeProviderContainer';

import Header from '@/components/header';

const fontRoboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${fontRoboto.variable} antialiased`}>
        <ThemeProviderContainer>
          <Header />
          {children}
        </ThemeProviderContainer>
      </body>
    </html>
  );
}
